package org.geosdi.geoplatform.services;

import javax.jws.WebService;
import org.geosdi.geoplatform.core.model.GPUser;
import org.geosdi.geoplatform.exception.IllegalParameterFault;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-06-23T21:19:24.588+02:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(endpointInterface = "org.geosdi.geoplatform.services.Greeter")
public class GreeterServiceImpl implements Greeter {
    
    @Override
    public java.lang.String greetMe(String value) {
        return "greetMe";
    }

    @Override
    public java.lang.String sayHi() {
        return "sayHi";
    }

//    /**
//     *
//     * @return
//     *     returns Greeter
//     */
//    @WebEndpoint(name = "GreeterPort")
//    public Greeter getGreeterPort() {
//        return super.getPort(GreeterPort, Greeter.class);
//    }
//
//    /**
//     * 
//     * @param features
//     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
//     * @return
//     *     returns Greeter
//     */
//    @WebEndpoint(name = "GreeterPort")
//    public Greeter getGreeterPort(WebServiceFeature... features) {
//        return super.getPort(GreeterPort, Greeter.class, features);
//    }

}
